#controllernode

    - name: Install NTP
      yum:
        name: ntp
        state: present

    - name: Start and enable NTP service
      service:
        name: ntpd
        state: started
        enabled: yes
        
    - name: Enabling OpenStack Repository
      yum:
        name: centos-release-openstack-train
        state: latest
    - name: Downloading and Installing repository
      yum:
        name: https://rdoproject.org/repos/rdo-release.rpm
        state: present
      ignore_error: true

    - name: Update Repository
      yum:
        name: '*'
        state: latest
        update_cache: true

    - name: Installing openstack
      yum:
        name:
          - openstack-selinux
          - python-openstackclient
          -openstack-utils
        
    - name: Install MariaDB server
      yum:
        name: mariadb-server
        state: present

    - name: Start and enable MariaDB service
      service:
        name: mariadb
        state: started
        enabled: yes
        
    - name: Install RabbitMQ server
      yum:
        name: rabbitmq-server
        state: present

    - name: Start and enable RabbitMQ service
      service:
        name: rabbitmq-server
        state: started
        enabled: yes
        
    - name: Install Memcached
      yum:
        name: memcached
        state: present

    - name: Start and enable Memcached service
      service:
        name: memcached
        state: started
        enabled: yes
        
    - name: Install Etcd
      yum:
        name: etcd
        state: present

    - name: Start and enable Etcd service
      service:
        name: etcd
        state: started
        enabled: yes
