#controllernode

    - name: Install NTP
      yum:
        name: ntp
        state: present

    - name: Start and enable NTP service
      service:
        name: ntpd
        state: started
        enabled: yes
        
    - name: Install common OpenStack packages
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - python3-openstackclient
        - mariadb-client
        - rabbitmq-server
        - etcd
        - memcached
        
    - name: Install MariaDB server
      yum:
        name: mariadb-server
        state: present

    - name: Start and enable MariaDB service
      service:
        name: mariadb
        state: started
        enabled: yes
        
    - name: Install RabbitMQ server
      yum:
        name: rabbitmq-server
        state: present

    - name: Start and enable RabbitMQ service
      service:
        name: rabbitmq-server
        state: started
        enabled: yes
        
    - name: Install Memcached
      yum:
        name: memcached
        state: present

    - name: Start and enable Memcached service
      service:
        name: memcached
        state: started
        enabled: yes
        
    - name: Install Etcd
      yum:
        name: etcd
        state: present

    - name: Start and enable Etcd service
      service:
        name: etcd
        state: started
        enabled: yes
