---

- hosts: all
  become: true
  pre_tasks: 

  - name: install updates (CentOS)
    tags: always
    package:
      name: '*'
      state: latest

  - name: install update (Ubuntu)
    tags: always
    package:
      upgrade: dist
      update_cache: yes
      
- hosts: compute_node 
  become: true
  roles:
    - compute_node
    
- hosts: controller_node
  become: true
  roles:
    - controller_node

